version: 2.1

orbs:
  win: circleci/windows@2.2.0
  
jobs:
   build:
     executor:
       name: win/default
     steps:
       - checkout
       - run: dotnet build
       - run: dotnet test C:\Users\alexw\source\repos\Card-Game-Repo\Card-Game.sln -r C:\test-results